#!/usr/bin/env python3
"""Generate go-live 301 redirect checklist and update _redirects / .htaccess from rename-mapping.json."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPPING_PATH = ROOT / "rename-mapping.json"
CHECKLIST_PATH = ROOT / "redirect-checklist.md"
REDIRECTS_PATH = ROOT / "_redirects"
HTACCESS_PATH = ROOT / ".htaccess"
SITE = "https://www.writingrodgerssolution.co.uk"

# Pages that exist on live sitemap but are not in rename-mapping (new content)
NEW_ONLY_SLUGS = ["about-us"]


def load_html_mappings() -> list[tuple[str, str]]:
    data = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    rows: list[tuple[str, str]] = []
    for old, new in sorted(data.items()):
        if not old.endswith(".html") or old == "index.html" or old == "404.html":
            continue
        if not new.endswith(".html"):
            continue
        slug = new[: -len(".html")]
        rows.append((old, f"/{slug}/"))
    return rows


def escape_apache_path(name: str) -> str:
    return re.sub(r"([.\-])", r"\\\1", name)


def build_redirect_lines(mappings: list[tuple[str, str]]) -> list[str]:
    lines: list[str] = []
    seen: set[str] = set()

    def add(from_path: str, to_path: str) -> None:
        key = (from_path.lower(), to_path)
        if key in seen:
            return
        seen.add(key)
        lines.append((from_path, to_path))

    add("/index.html", "/")

    for old_name, new_path in mappings:
        kebab = old_name.lower()
        add(f"/{old_name}", new_path)
        if kebab != old_name:
            add(f"/{kebab}", new_path)

    for slug in NEW_ONLY_SLUGS:
        add(f"/{slug}.html", f"/{slug}/")

    lines.sort(key=lambda pair: pair[0].lower())
    return [f"{src}  {dst}  301" for src, dst in lines]


def build_htaccess(mappings: list[tuple[str, str]]) -> str:
    header = """# 301 redirects: legacy .html URLs -> folder URLs
# Generated by scripts/generate-redirect-checklist.py — do not edit by hand
RewriteEngine On
"""
    rules: list[str] = ["RewriteRule ^index\\.html$ / [R=301,L]"]
    seen: set[str] = set()

    for old_name, new_path in mappings:
        for name in {old_name, old_name.lower()}:
            if name in seen:
                continue
            seen.add(name)
            pattern = escape_apache_path(name)
            dest = new_path if new_path.endswith("/") else f"{new_path}/"
            rules.append(
                f"RewriteRule ^{pattern}$ {dest} [R=301,L]"
            )

    for slug in NEW_ONLY_SLUGS:
        rules.append(f"RewriteRule ^{slug}\\.html$ /{slug}/ [R=301,L]")

    rules.sort(key=str.lower)
    return header + "\n".join(rules) + "\n"


def build_checklist_markdown(mappings: list[tuple[str, str]], redirect_count: int) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Go-live redirect checklist — Writing Rodgers Solution",
        "",
        f"Generated **{generated}** from `rename-mapping.json`. Regenerate:",
        "",
        "```bash",
        "python3 scripts/generate-redirect-checklist.py",
        "```",
        "",
        "Preserve SEO when switching from the **live Viamagus** site (Pascal-Case `.html` URLs) "
        "to the **new static** site (folder URLs). Every indexed old URL should return **301** "
        "to the matching new URL.",
        "",
        f"**Redirect rules written:** {redirect_count} (in `_redirects` and `.htaccess`)",
        "",
        "## Before cutover",
        "",
        "- [ ] Point DNS to GitHub Pages (or host that serves this repo)",
        "- [ ] Set custom domain to `www.writingrodgerssolution.co.uk` (match canonicals in HTML)",
        "- [ ] Fix `robots.txt`: `Sitemap: https://www.writingrodgerssolution.co.uk/sitemap.xml`",
        "- [ ] Deploy new `sitemap.xml` (slug URLs only — no `robots.txt`, no `/404.html`)",
        "- [ ] Enable **301** redirects (see hosting notes below)",
        "- [ ] Google Search Console → submit new sitemap → inspect a few old URLs after 48h",
        "",
        "## Hosting: how redirects run",
        "",
        "| Host | File | Notes |",
        "| --- | --- | --- |",
        "| **Cloudflare** (recommended in front of GitHub Pages) | Bulk Redirect Rules or Transform Rules | Import CSV from table below; supports Pascal-Case paths |",
        "| **Netlify / Cloudflare Pages** | `_redirects` in repo root | Already updated by this script |",
        "| **Apache** | `.htaccess` in repo root | Already updated by this script |",
        "| **GitHub Pages only** (no CDN) | No server redirects | Use Cloudflare in front, or add stub `.html` files (not generated here) |",
        "",
        "**Important:** Live Google results use **Pascal-Case** paths like `/BPP-Assignment-Help.html`. "
        "Lowercase-only redirects are not enough.",
        "",
        "## Full 301 map (old → new)",
        "",
        "| Old URL (live / indexed) | New URL (repo) |",
        "| --- | --- |",
        f"| `{SITE}/` | `{SITE}/` |",
        f"| `{SITE}/index.html` | `{SITE}/` |",
    ]

    for old_name, new_path in mappings:
        lines.append(
            f"| `{SITE}/{old_name}` | `{SITE}{new_path}` |"
        )
        kebab = old_name.lower()
        if kebab != old_name:
            lines.append(
                f"| `{SITE}/{kebab}` | `{SITE}{new_path}` |"
            )

    for slug in NEW_ONLY_SLUGS:
        lines.append(
            f"| `{SITE}/{slug}.html` (if used) | `{SITE}/{slug}/` |"
        )
        lines.append(
            f"| — | `{SITE}/{slug}/` (**new page**, no live predecessor) |"
        )

    lines.extend(
        [
            "",
            "## Pages without a legacy URL",
            "",
            "| New URL | Note |",
            "| --- | --- |",
        ]
    )
    for slug in NEW_ONLY_SLUGS:
        lines.append(f"| `{SITE}/{slug}/` | New in static build; add internal links + sitemap only |")

    lines.extend(
        [
            "",
            "## After cutover — smoke tests",
            "",
            "Run these (expect **301** then **200** on the new URL):",
            "",
            "```bash",
            "curl -sI 'https://www.writingrodgerssolution.co.uk/BPP-Assignment-Help.html' | head -5",
            "curl -sI 'https://www.writingrodgerssolution.co.uk/bpp-assignment-help.html' | head -5",
            "curl -sI 'https://www.writingrodgerssolution.co.uk/bpp-assignment-help/' | head -5",
            "```",
            "",
            "- [ ] Homepage loads new WR layout (not Viamagus)",
            "- [ ] `/bpp-assignment-help/` returns 200 with JSON-LD in source",
            "- [ ] Old Pascal-Case URL redirects to slug folder",
            "- [ ] Search Console: no spike in 404s after 1 week",
            "",
            "## `_redirects` format (Netlify / Cloudflare Pages)",
            "",
            "```",
            "# from_path  to_path  status",
            "/BPP-Assignment-Help.html  /bpp-assignment-help/  301",
            "```",
            "",
            "See `_redirects` in repo root for the full list.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    mappings = load_html_mappings()
    redirect_lines = build_redirect_lines(mappings)

    REDIRECTS_PATH.write_text("\n".join(redirect_lines) + "\n", encoding="utf-8")
    HTACCESS_PATH.write_text(build_htaccess(mappings), encoding="utf-8")
    CHECKLIST_PATH.write_text(
        build_checklist_markdown(mappings, len(redirect_lines)), encoding="utf-8"
    )

    print(f"Wrote {CHECKLIST_PATH.relative_to(ROOT)}")
    print(f"Updated {REDIRECTS_PATH.relative_to(ROOT)} ({len(redirect_lines)} rules)")
    print(f"Updated {HTACCESS_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
